-- VetBot privacy-by-design support tables.
-- No prompt, response, owner name, contact detail or medical narrative is stored here.

create table if not exists public.vetbot_audit_logs (
  audit_id bigint generated by default as identity primary key,
  actor_id uuid not null default auth.uid(),
  actor_role text not null check (actor_role in ('clinic_admin','vet','nurse','secretary','owner')),
  mode text not null check (mode in ('dashboard','schedule','digital-care','inventory','medical-record','clients','reports','portal')),
  tool_names text[] not null default '{}',
  redaction_categories text[] not null default '{}',
  redaction_count integer not null default 0 check (redaction_count >= 0),
  outcome text not null check (outcome in ('success','failed','blocked')),
  provider text not null default 'gemini',
  model_name text,
  notice_version text not null,
  error_code text,
  created_at timestamptz not null default now()
);

create index if not exists vetbot_audit_actor_created_idx on public.vetbot_audit_logs(actor_id, created_at desc);
create index if not exists vetbot_audit_created_idx on public.vetbot_audit_logs(created_at desc);
alter table public.vetbot_audit_logs enable row level security;

drop policy if exists "vetbot audit insert own" on public.vetbot_audit_logs;
create policy "vetbot audit insert own" on public.vetbot_audit_logs for insert to authenticated
with check (actor_id = auth.uid());

drop policy if exists "vetbot audit admin read" on public.vetbot_audit_logs;
create policy "vetbot audit admin read" on public.vetbot_audit_logs for select to authenticated
using (exists (select 1 from public.staff s where s.auth_user_id = auth.uid() and s.is_active = true and s.role = 'clinic_admin'));

create table if not exists public.vetbot_feedback (
  feedback_id bigint generated by default as identity primary key,
  actor_id uuid not null default auth.uid(),
  mode text not null check (mode in ('dashboard','schedule','digital-care','inventory','medical-record','clients','reports','portal')),
  helpful boolean not null,
  used_tools text[] not null default '{}',
  notice_version text not null,
  created_at timestamptz not null default now()
);
create index if not exists vetbot_feedback_created_idx on public.vetbot_feedback(created_at desc);
alter table public.vetbot_feedback enable row level security;

drop policy if exists "vetbot feedback insert own" on public.vetbot_feedback;
create policy "vetbot feedback insert own" on public.vetbot_feedback for insert to authenticated
with check (actor_id = auth.uid());

drop policy if exists "vetbot feedback admin read" on public.vetbot_feedback;
create policy "vetbot feedback admin read" on public.vetbot_feedback for select to authenticated
using (exists (select 1 from public.staff s where s.auth_user_id = auth.uid() and s.is_active = true and s.role = 'clinic_admin'));

create table if not exists public.vetbot_knowledge (
  knowledge_id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  content text not null,
  source_label text not null default 'נוהל מרפאה',
  is_active boolean not null default true,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vetbot_knowledge_no_contact check (
    content !~* '[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}'
    and content !~ '05[0-9][ -]?[0-9]{3}[ -]?[0-9]{4}'
  )
);
alter table public.vetbot_knowledge enable row level security;

drop policy if exists "vetbot knowledge staff read" on public.vetbot_knowledge;
create policy "vetbot knowledge staff read" on public.vetbot_knowledge for select to authenticated
using (exists (select 1 from public.staff s where s.auth_user_id = auth.uid() and s.is_active = true));

drop policy if exists "vetbot knowledge admin manage" on public.vetbot_knowledge;
create policy "vetbot knowledge admin manage" on public.vetbot_knowledge for all to authenticated
using (exists (select 1 from public.staff s where s.auth_user_id = auth.uid() and s.is_active = true and s.role = 'clinic_admin'))
with check (exists (select 1 from public.staff s where s.auth_user_id = auth.uid() and s.is_active = true and s.role = 'clinic_admin'));

insert into public.vetbot_knowledge (slug, title, content, source_label)
values
  ('vetbot-safety', 'כללי בטיחות של VetBot', 'VetBot הוא כלי מסייע. אין לבצע אבחון חדש, לקבוע מינון חדש, לשלוח הודעה או לשנות רשומה רפואית ללא בדיקה ואישור של איש צוות מורשה.', 'מדיניות VetBot'),
  ('digital-emergency', 'הסלמת פנייה דחופה', 'ביטויים המעידים על קושי נשימתי, דימום משמעותי, אובדן הכרה, פרכוס, חשד להרעלה או התמוטטות דורשים בדיקה מיידית של איש צוות רפואי ואין להמתין לתשובת בוט.', 'נוהל מרפאה דיגיטלית'),
  ('privacy-minimization', 'צמצום מידע בשימוש ב-AI', 'אין להזין או להעביר ל-VetBot תעודת זהות, כתובת, טלפון, דואר אלקטרוני, פרטי תשלום, סיסמאות או קישורים פרטיים. המערכת משחירה מזהים לפני עיבוד חיצוני.', 'מדיניות פרטיות')
on conflict (slug) do update set title = excluded.title, content = excluded.content, source_label = excluded.source_label, updated_at = now();

comment on table public.vetbot_audit_logs is 'Metadata-only VetBot audit trail. Retain for at least 24 months when Regulation 10 applies; do not add prompt or response columns.';
comment on table public.vetbot_knowledge is 'Non-personal clinic knowledge only. Do not store owner, staff or patient identifiers.';

