-- Reliable live refresh and server-authorized payment settlement.
-- Portal payments in this graduation-project build are a clearly labelled
-- simulation. A production gateway must replace the owner RPC with a verified
-- provider webhook before real card details or money are accepted.

do $$
declare
  table_name text;
  live_tables text[] := array[
    'appointments', 'patients', 'owners', 'payments', 'conversations',
    'messages', 'lab_orders', 'hospitalizations', 'inventory', 'vaccinations'
  ];
begin
  foreach table_name in array live_tables loop
    if to_regclass(format('public.%I', table_name)) is not null
      and not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = table_name
      ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
  end loop;
end $$;

-- Remove broad prototype policies that could let one authenticated user see or
-- mutate another user's medical/billing rows. The explicit staff and owner
-- policies from 202607150002_myvet_rls_hardening.sql remain in force.
do $$
declare
  policy_row record;
  protected_tables text[] := array[
    'staff', 'owners', 'patients', 'appointments', 'payments', 'payment_items',
    'medical_visits', 'physical_exams', 'medical_problems', 'differential_diagnoses',
    'prescriptions', 'lab_orders', 'documents', 'hospitalizations', 'conversations',
    'messages', 'message_attachments', 'video_sessions', 'notifications', 'reminders',
    'vaccinations', 'inventory', 'service_catalog'
  ];
begin
  for policy_row in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any(protected_tables)
      and (policyname ilike 'myvet_demo_%' or policyname ilike 'allow anon%')
  loop
    execute format('drop policy if exists %I on public.%I', policy_row.policyname, policy_row.tablename);
  end loop;
end $$;

revoke all privileges on table public.payments from anon;
revoke all privileges on table public.payment_items from anon;

create table if not exists public.payment_transactions (
  transaction_id bigint generated by default as identity primary key,
  payment_id bigint not null references public.payments(payment_id) on delete restrict,
  owner_id text not null references public.owners(owner_id) on delete restrict,
  amount numeric(12, 2) not null check (amount >= 0),
  payment_method text not null check (payment_method in ('cash', 'credit', 'bit', 'bank_transfer', 'other', 'portal_demo')),
  tendered_amount numeric(12, 2) check (tendered_amount is null or tendered_amount >= 0),
  change_amount numeric(12, 2) not null default 0 check (change_amount >= 0),
  source text not null check (source in ('owner_portal_demo', 'staff')),
  processed_by uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists payment_transactions_payment_created_idx
  on public.payment_transactions(payment_id, created_at desc);
create index if not exists payment_transactions_owner_created_idx
  on public.payment_transactions(owner_id, created_at desc);

alter table public.payment_transactions enable row level security;
revoke all privileges on table public.payment_transactions from anon;
revoke insert, update, delete on table public.payment_transactions from authenticated;
grant select on table public.payment_transactions to authenticated;
grant all privileges on table public.payment_transactions to service_role;

drop policy if exists "myvet_payment_transactions_staff_select" on public.payment_transactions;
create policy "myvet_payment_transactions_staff_select"
  on public.payment_transactions for select to authenticated
  using ((select public.myvet_is_active_staff()));

drop policy if exists "myvet_payment_transactions_owner_select" on public.payment_transactions;
create policy "myvet_payment_transactions_owner_select"
  on public.payment_transactions for select to authenticated
  using ((select public.myvet_owner_matches(owner_id)));

create or replace function public.myvet_owner_settle_demo_payment(requested_payment_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_payment public.payments%rowtype;
  settled_at timestamptz := now();
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select * into target_payment
  from public.payments
  where payments.payment_id = requested_payment_id
  for update;

  if not found then
    raise exception 'PAYMENT_NOT_FOUND';
  end if;

  if not public.myvet_owner_matches(target_payment.owner_id) then
    raise exception 'PAYMENT_NOT_OWNED';
  end if;

  if target_payment.status = 'paid' then
    return jsonb_build_object(
      'payment_id', target_payment.payment_id,
      'status', target_payment.status,
      'amount', target_payment.amount,
      'already_paid', true
    );
  end if;

  if target_payment.status not in ('unpaid', 'partial') then
    raise exception 'PAYMENT_NOT_OPEN';
  end if;

  update public.payments
  set status = 'paid',
      payment_method = 'portal_demo',
      paid_at = settled_at
  where payment_id = target_payment.payment_id;

  insert into public.payment_transactions (
    payment_id, owner_id, amount, payment_method, tendered_amount,
    change_amount, source, processed_by, created_at
  ) values (
    target_payment.payment_id, target_payment.owner_id, target_payment.amount,
    'portal_demo', target_payment.amount, 0, 'owner_portal_demo', auth.uid(), settled_at
  );

  return jsonb_build_object(
    'payment_id', target_payment.payment_id,
    'status', 'paid',
    'amount', target_payment.amount,
    'paid_at', settled_at,
    'already_paid', false
  );
end;
$$;

create or replace function public.myvet_staff_settle_payment(
  requested_payment_id bigint,
  requested_method text,
  tendered_amount numeric default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_payment public.payments%rowtype;
  normalized_method text := lower(trim(coalesce(requested_method, '')));
  calculated_change numeric(12, 2) := 0;
  settled_at timestamptz := now();
begin
  if auth.uid() is null or not public.myvet_is_active_staff() then
    raise exception 'STAFF_REQUIRED';
  end if;

  if normalized_method not in ('cash', 'credit', 'bit', 'bank_transfer', 'other') then
    raise exception 'INVALID_PAYMENT_METHOD';
  end if;

  select * into target_payment
  from public.payments
  where payments.payment_id = requested_payment_id
  for update;

  if not found then
    raise exception 'PAYMENT_NOT_FOUND';
  end if;

  if target_payment.status = 'paid' then
    raise exception 'PAYMENT_ALREADY_PAID';
  end if;

  if target_payment.status not in ('unpaid', 'partial') then
    raise exception 'PAYMENT_NOT_OPEN';
  end if;

  if normalized_method = 'cash' then
    if tendered_amount is null or tendered_amount < target_payment.amount then
      raise exception 'INSUFFICIENT_CASH';
    end if;
    calculated_change := tendered_amount - target_payment.amount;
  end if;

  update public.payments
  set status = 'paid',
      payment_method = normalized_method,
      paid_at = settled_at
  where payment_id = target_payment.payment_id;

  insert into public.payment_transactions (
    payment_id, owner_id, amount, payment_method, tendered_amount,
    change_amount, source, processed_by, created_at
  ) values (
    target_payment.payment_id, target_payment.owner_id, target_payment.amount,
    normalized_method,
    case when normalized_method = 'cash' then tendered_amount else null end,
    calculated_change, 'staff', auth.uid(), settled_at
  );

  return jsonb_build_object(
    'payment_id', target_payment.payment_id,
    'status', 'paid',
    'amount', target_payment.amount,
    'payment_method', normalized_method,
    'change_amount', calculated_change,
    'paid_at', settled_at
  );
end;
$$;

revoke all on function public.myvet_owner_settle_demo_payment(bigint) from public;
revoke all on function public.myvet_staff_settle_payment(bigint, text, numeric) from public;
grant execute on function public.myvet_owner_settle_demo_payment(bigint) to authenticated;
grant execute on function public.myvet_staff_settle_payment(bigint, text, numeric) to authenticated;
grant execute on function public.myvet_owner_settle_demo_payment(bigint) to service_role;
grant execute on function public.myvet_staff_settle_payment(bigint, text, numeric) to service_role;

comment on function public.myvet_owner_settle_demo_payment(bigint) is
  'Graduation-project payment simulation. Replace with a verified payment-provider webhook before production use.';
